export const defaultState = {
  auth: {
    userName: 'чел 1',
    email: '',
  },
  boards: [
    {
      id: 1,
      title: 'Доска 1',
      description: 'Описание доски 1',
      context: 'Контекст доски 1',
      role: 'Админ',
      allowAnonymous: true,
      autoApprove: false,
      members: [
        { id: 1, name: 'чел 1', role: 'Админ' },
        { id: 2, name: 'чел 2', role: 'Модератор' },
        { id: 3, name: 'чел 3', role: 'Участник' },
      ],
    },
    {
      id: 2,
      title: 'Доска 2',
      description: 'Описание доски 2',
      context: 'Контекст доски 2',
      role: 'Участник',
      allowAnonymous: true,
      autoApprove: true,
      members: [
        { id: 4, name: 'чел 1', role: 'Участник' },
        { id: 5, name: 'чел 4', role: 'Админ' },
      ],
    },
  ],
  ideas: [
    {
      id: 1,
      boardId: 1,
      title: 'Идея 1',
      description: 'Описание идеи 1. Более длинный текст обрезается в карточке и полностью открывается в модальном окне.',
      status: 'approved',
      isAnonymous: true,
      author: 'чел 1',
      createdAt: 'сегодня',
      votesYes: 8,
      votesNo: 2,
      rejectionReason: '',
    },
    {
      id: 2,
      boardId: 1,
      title: 'Идея 2',
      description: 'Описание идеи 2',
      status: 'approved',
      isAnonymous: false,
      author: 'чел 2',
      createdAt: 'вчера',
      votesYes: 5,
      votesNo: 4,
      rejectionReason: '',
    },
    {
      id: 3,
      boardId: 1,
      title: 'Идея 3',
      description: 'Описание идеи 3',
      status: 'pending',
      isAnonymous: true,
      author: 'чел 3',
      createdAt: '16 апр',
      votesYes: 0,
      votesNo: 0,
      rejectionReason: '',
    },
    {
      id: 4,
      boardId: 1,
      title: 'Идея 4',
      description: 'Описание идеи 4',
      status: 'rejected',
      isAnonymous: false,
      author: 'чел 2',
      createdAt: '15 апр',
      votesYes: 0,
      votesNo: 0,
      rejectionReason: 'Причина отклонения 1',
    },
  ],
}
